# Generated by Django 4.1 on 2022-08-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('categoria', models.CharField(max_length=2)),
                ('domicilio', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('fecha_disponible', models.DateField()),
                ('detalle', models.CharField(max_length=300)),
            ],
        ),
    ]
