# Generated by Django 4.1 on 2022-08-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_y_nombre', models.CharField(max_length=40)),
                ('referencia', models.CharField(max_length=20)),
                ('telefono', models.IntegerField()),
                ('domicilio_legal', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ficha_tecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra', models.CharField(max_length=40)),
                ('ubicacion', models.CharField(max_length=30)),
                ('superficie', models.IntegerField()),
                ('construccion', models.DateField()),
                ('plazos', models.CharField(max_length=20)),
            ],
        ),
    ]
